#!/bin/bash

DEFINE_PACKAGE_CROSS=yes
DEFINE_PACKAGE_TAR=flac-1.2.1.tar.gz
DEFINE_PACKAGE_NAME=flac
DEFINE_PACKAGE_VERSION=1.2.1
DEFINE_PACKAGE_SOURCE=

# For ipkg
DEFINE_PACKAGE_STABLE=yes
DEFINE_PACKAGE_PRIORITY=optional
DEFINE_PACKAGE_DEPENDS=
DEFINE_PACKAGE_SECTION=Multimedia
DEFINE_PACKAGE_MAINTAINER="HuayaMicro Software Team"
DEFINE_PACKAGE_DESCRIPTION="Flac library."

DEFINE_LUPC=../..
. ${DEFINE_LUPC}/build_setting.sh

# For configure
DEFINE_CONFIGURE_ENV=
DEFINE_CONFIGURE_CMD="./configure "
DEFINE_CONFIGURE_FLAGS="--host=${DEFINE_HOST}  --with-html-dir=/tmp/dump --disable-cpplibs"

. ${DEFINE_LUPC}/build_rule.sh
