#!/bin/bash

# Default setting
DEFINE_HOST="mips-linux-gnu"
DEFINE_CFLAGS="-EL -march=24kef2_1 -mtune=24kef2_1 -O3 -I =/el/usr/include -DSTDC_HEADER ${DEFINE_COMPILER_CFLAGS}"
DEFINE_CXXFLAGS="-EL -march=24kef2_1 -mtune=24kef2_1 -O3 -I =/el/usr/include -DSTDC_HEADER ${DEFINE_COMPILER_CXXFLAGS}"
DEFINE_LDFLAGS="-EL -march=24kef2_1 -mtune=24kef2_1 ${DEFINE_COMPILER_LDFLAGS}"

DEFINE_GCC_SYSROOT_TMP=`${DEFINE_HOST}-gcc ${DEFINE_CFLAGS} --print-sysroot`
DEFINE_GCC_SYSROOT=`cd ${DEFINE_GCC_SYSROOT_TMP} && pwd`

DEFINE_ROOT=`pwd`
DEFINE_SOURCE=${DEFINE_ROOT}/${DEFINE_PACKAGE_NAME}-${DEFINE_PACKAGE_VERSION}
DEFINE_BINARY=${DEFINE_ROOT}/${DEFINE_PACKAGE_NAME}-binary
DEFINE_LOG_TITLE="LUPC_LOG: "

DEFINE_PKG_BINARY=${DEFINE_ROOT}/${DEFINE_PACKAGE_NAME}-binary
DEFINE_PKG_ROOT=${DEFINE_ROOT}/${DEFINE_LUPC}/../Release/packages

#DEFINE_GCC_ROOT=$(dirname $(which ${DEFINE_HOST}-gcc))/..
#DEFINE_GCC_PREFIX=${DEFINE_GCC_ROOT}/mips-linux-gnu
#export PKG_CONFIG_PATH=${DEFINE_GCC_PREFIX}/lib/pkgconfig

export PKG_CONFIG_PATH=''
export PKG_CONFIG_SYSROOT_DIR=${DEFINE_GCC_SYSROOT}
export PKG_CONFIG_LIBDIR=${PKG_CONFIG_SYSROOT_DIR}/usr/lib/pkgconfig:${PKG_CONFIG_SYSROOT_DIR}/usr/local/lib/pkgconfig:${PKG_CONFIG_SYSROOT_DIR}/usr/share/lib/pkgconfig

