#!/bin/bash

DEFINE_PACKAGE_CROSS=yes
DEFINE_PACKAGE_TAR=jpegsrc.v6b.tar.gz
DEFINE_PACKAGE_NAME=jpeg
DEFINE_PACKAGE_VERSION=6b
DEFINE_PACKAGE_SOURCE=

# For ipkg
DEFINE_PACKAGE_STABLE=yes
DEFINE_PACKAGE_PRIORITY=optional
DEFINE_PACKAGE_DEPENDS=
DEFINE_PACKAGE_SECTION=Misc
DEFINE_PACKAGE_MAINTAINER="HuayaMicro Software Team"
DEFINE_PACKAGE_DESCRIPTION="compress/decompress libraries."
DEFINE_COMPILER_CFLAGS=" -fPIC"
DEFINE_COMPILER_CXXFLAGS=" -fPIC"

DEFINE_LUPC=../..
. ${DEFINE_LUPC}/build_setting.sh

# For configure
DEFINE_CONFIGURE_ENV=
DEFINE_CONFIGURE_CMD="./configure"
DEFINE_CONFIGURE_FLAGS="--build=i386-linux --host=${DEFINE_HOST}"
DEFINE_INSTALL_CMD="make DESTDIR=${DEFINE_BINARY} install-lib"

. ${DEFINE_LUPC}/build_rule.sh
