#!/bin/bash

DEFINE_PACKAGE_CROSS=yes
DEFINE_PACKAGE_TAR=ntfs-3g_ntfsprogs-2013.1.13.tgz
DEFINE_PACKAGE_NAME=ntfs-3g_ntfsprogs
DEFINE_PACKAGE_VERSION=2013.1.13
DEFINE_PACKAGE_SOURCE=

# For ipkg
DEFINE_PACKAGE_STABLE=yes
DEFINE_PACKAGE_PRIORITY=optional
DEFINE_PACKAGE_DEPENDS=
DEFINE_PACKAGE_SECTION=Communications
DEFINE_PACKAGE_MAINTAINER="WZ-tech Software Team"
DEFINE_PACKAGE_DESCRIPTION="User space NTFS driver."

DEFINE_LUPC=../..
. ${DEFINE_LUPC}/build_setting.sh

# For configure
DEFINE_CONFIGURE_ENV=
DEFINE_CONFIGURE_CMD="./configure"
DEFINE_CONFIGURE_FLAGS="--host=${DEFINE_HOST} "

DEFINE_INSTALL_CMD=${DEFINE_SOURCE}/../install_ntfs-3g.sh
DEFINE_INSTALL_FLAGS="${DEFINE_SOURCE} ${DEFINE_BINARY}"

. ${DEFINE_LUPC}/build_rule.sh
